"""Finding type labels, categories, severities and plain-language guidance. Sentence case, no legal citations beyond rule names."""
from __future__ import annotations

# finding_type: (label, category, severity, rule_ref, rule_text, what_to_do, draft_kind)
META: dict[str, tuple[str, str, str, str, str, str, str]] = {
    "AMOUNT_MISMATCH": ("Booked amount differs from invoice", "matching", "medium", "Books must equal the invoice",
                        "The ledger booking and the invoice it records should carry the same total.",
                        "Correct the ledger entry so it equals the invoice total.", "journal_entry"),
    "DATE_MISMATCH": ("Booked in a different period", "matching", "low", "Book in the invoice month",
                      "An invoice should be booked in the Return period of its date, or tax lands in the wrong month.",
                      "Move the booking to the month of the invoice date.", "journal_entry"),
    "INVOICE_ID_MISMATCH": ("Invoice number typed differently", "matching", "medium", "Invoice number must match",
                            "The reference on the other record is a variant of the real invoice number.",
                            "Fix the reference so both records carry the same invoice number.", "journal_entry"),
    "PAYMENT_AMOUNT_MISMATCH": ("Paid amount differs from invoice", "matching", "medium", "Payment must equal the invoice",
                                "The bank amount differs from the invoice total and no second payment explains the gap.",
                                "Check with the Party and book the difference.", "journal_entry"),
    "PAYMENT_BEFORE_INVOICE": ("Paid before the invoice date", "matching", "medium", "Payment follows the invoice",
                               "Money moved before the invoice was dated: an unrecorded advance or a backdated invoice.",
                               "Record the advance, or confirm the invoice date with the Party.", "journal_entry"),
    "MISSING_LEDGER_ENTRY": ("Invoice never booked", "missing", "high", "Every invoice is booked",
                             "The invoice exists but no ledger entry records it, so its tax is missing from the books.",
                             "Book the invoice in the ledger.", "journal_entry"),
    "ORPHAN_LEDGER_ENTRY": ("Booking with no invoice", "missing", "medium", "Every booking has an invoice",
                            "The ledger entry refers to an invoice number that is not in the invoice register.",
                            "Find the invoice or reverse the entry.", "journal_entry"),
    "PAID_NOT_IN_BANK": ("Payment booked but not in bank", "missing", "high", "Booked payments appear in the bank",
                         "The ledger shows the money moving but the bank statement has no such line.",
                         "Trace the payment or reverse the ledger entry.", "journal_entry"),
    "UNMATCHED_BANK_TXN": ("Bank entry with no invoice", "missing", "medium", "Every bank line has a document",
                           "A known Party moved money but no invoice or booking explains it.",
                           "Ask the Party what the payment is for and book it.", "journal_entry"),
    "MISSING_IN_2B": ("Supplier has not reported this invoice", "missing", "high", "Credit must appear in GSTR-2B",
                      "Input tax credit can be claimed only when the Supplier reports the invoice and it shows in GSTR-2B.",
                      "Ask the Supplier to report the invoice in their return. Hold the credit until it appears.", "supplier_email"),
    "MISSING_IN_BOOKS": ("Credit in GSTR-2B not in your books", "missing", "medium", "GSTR-2B shows credit you can claim",
                         "The Supplier reported a purchase to you that is not in the books, so its credit has not been claimed.",
                         "Get the invoice from the Supplier, book it and claim the credit.", "journal_entry"),
    "GSTR2B_VALUE_MISMATCH": ("Supplier reported a different amount", "missing", "medium", "Books must agree with GSTR-2B",
                              "The Supplier reported a different taxable value than the invoice in the books.",
                              "Ask the Supplier to amend their return, or correct the booking.", "supplier_email"),
    "PERIOD_SHIFT": ("Supplier reported in another month", "missing", "low", "Credit follows the Supplier's filing month",
                     "The Supplier reported this invoice in a later Return period, so the credit shows in that month.",
                     "Claim the credit in the month it appears in GSTR-2B.", "journal_entry"),
    "DUPLICATE_INVOICE": ("Invoice entered twice", "duplicate", "high", "One invoice, one entry",
                          "Same Party, same value and tax, almost the same date, under a new invoice number.",
                          "Cancel the second entry so tax is not counted twice.", "credit_note_request"),
    "DUPLICATE_LEDGER_ENTRY": ("Booked twice", "duplicate", "high", "One invoice, one booking",
                               "Two ledger entries record the same invoice.",
                               "Reverse the second booking.", "journal_entry"),
    "DUPLICATE_PAYMENT": ("Paid twice", "duplicate", "high", "One invoice, one payment",
                          "A second bank line with the same amount and Party settles an invoice already paid.",
                          "Ask for a refund or adjust it against the next invoice.", "journal_entry"),
    "WRONG_TAX_RATE": ("Wrong GST rate", "tax", "high", "Effective rate on the invoice date",
                       "The GST rate must be the one in force for that HSN code on the invoice date.",
                       "Issue or request a credit note for the difference and correct the rate.", "customer_credit_note"),
    "WRONG_TAX_TYPE": ("IGST and CGST plus SGST mixed up", "tax", "high", "Tax type follows place of supply",
                       "A supply inside one state carries CGST plus SGST. A supply across states carries IGST.",
                       "Reissue the invoice with the right tax type.", "customer_credit_note"),
    "TAX_CALC_ERROR": ("Tax does not add up", "tax", "medium", "Tax equals taxable value times rate",
                       "The rate is right but the tax amount is not the taxable value times that rate.",
                       "Correct the tax amount on the invoice.", "customer_credit_note"),
    "EXEMPT_ITEM_TAXED": ("Tax charged on an exempt item", "tax", "medium", "Exempt items carry no tax",
                          "The rate table marks this HSN code as exempt, but the invoice charges tax.",
                          "Issue a credit note for the tax charged.", "customer_credit_note"),
    "TAXABLE_ITEM_ZERO_TAX": ("No tax on a taxable item", "tax", "high", "Taxable items carry tax",
                              "The rate table gives this HSN code a rate above zero, but the invoice charges none.",
                              "Raise a debit note for the tax that was not charged.", "customer_credit_note"),
    "INVALID_GSTIN": ("GSTIN is not valid", "tax", "high", "GSTIN check character",
                      "The GSTIN on the invoice has the wrong length or fails its check character.",
                      "Get the correct GSTIN from the Party and reissue the invoice.", "supplier_email"),
    "CANCELLED_GSTIN": ("Supplier's GSTIN is cancelled", "tax", "critical", "Supplier must hold an active GSTIN",
                        "The invoice is dated on or after the day the Supplier's registration was cancelled.",
                        "Stop the credit, and ask the Supplier for proof of an active registration.", "supplier_email"),
    "RULE_37_UNPAID_180": ("Supplier unpaid for over 180 days", "tax", "critical", "Rule 37: pay within 180 days",
                           "Credit on a purchase is kept only if the Supplier is paid within 180 days of the invoice date.",
                           "Pay the Supplier, or reverse the credit until it is paid.", "journal_entry"),
    "CIRCULAR_FLOW": ("Money went out and came back", "anomaly", "critical", "Round trip with no invoice",
                      "A round amount left for a Party with no invoice and the same amount came back within days.",
                      "Ask for the business reason and the documents behind both transfers.", "journal_entry"),
    "OUTLIER_AMOUNT": ("Far larger than usual", "anomaly", "medium", "Unusual for this Party",
                       "The invoice value is many times this Party's usual invoice.",
                       "Confirm the order and delivery before accepting it.", "journal_entry"),
    "ROUND_AMOUNT_SPIKE": ("Large round amount", "anomaly", "medium", "Perfectly round value",
                           "Real invoices rarely land on a large, perfectly round value.",
                           "Check the supporting order and delivery papers.", "journal_entry"),
    "THRESHOLD_SPLITTING": ("Split to stay under the approval limit", "anomaly", "high", "Approval limit",
                            "Several invoices from one Supplier in a few days, each just under the approval limit.",
                            "Review them together as one purchase.", "journal_entry"),
    "VENDOR_BURST": ("Burst of small invoices", "anomaly", "medium", "Unusual timing",
                     "Many small invoices from one Supplier in a very short time.",
                     "Check the invoices against deliveries.", "journal_entry"),
    "WEEKEND_LARGE_TXN": ("Large invoice on a Sunday", "anomaly", "low", "Unusual date",
                          "An unusually large invoice dated on a Sunday.",
                          "Confirm the date and the supply.", "journal_entry"),
    "PAN_LINKED_RING": ("Supplier and Customer share an owner", "anomaly", "critical", "Same PAN behind two registrations",
                        "A Supplier you buy from and a Customer you sell to carry the same PAN, so one owner sits on both sides.",
                        "Review every invoice with both Parties before claiming credit.", "journal_entry"),
    "ITC_OVERCLAIM": ("More credit claimed than invoices support", "filing", "critical", "Return must equal the books",
                      "The return claims more input tax credit than the purchase invoices carry.",
                      "Reverse the extra credit in the next return.", "journal_entry"),
    "UNDER_REPORTED_OUTPUT_TAX": ("Return shows less tax than sales", "filing", "critical", "Return must equal the books",
                                  "The return declares less output tax than the sales invoices carry.",
                                  "Declare the missing tax in the next return.", "journal_entry"),
    "TAX_SHORT_PAYMENT": ("Paid less tax than the return says", "filing", "critical", "Tax paid must equal tax declared",
                          "The tax payment in the bank is lower than the net tax the return declares.",
                          "Pay the balance.", "journal_entry"),
    "LATE_FILING": ("Return filed late", "filing", "medium", "File by the due date",
                    "The return was filed after its due date.",
                    "File on time; check what is owed for the delay.", "journal_entry"),
}

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


def label(finding_type: str) -> str:
    return META[finding_type][0]
